services:
  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"  
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge